apiVersion: v1
kind: Service
metadata: 
  name: app-deployment
spec: 
  type: NodePort
  selector:
    labels:
      app: custom
  ports:
   - protocol: TCP
     targetPort: 80
     port: 80
     nodePort: 30008
